version: '3.8'

services:
  db-pg:
    container_name: db_postgres
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - dev.env
    ports:
      - '5432:5432'
    networks:
      - api_network
    volumes:
      - ./pkg/database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-redis:
    container_name: db_redis
    image: redis:alpine
    restart: unless-stopped
    env_file:
      - dev.env
    ports:
      - '6379:6379'
    depends_on:
      - db-pg
    networks:
      - api_network


networks:
  api_network:
    driver: bridge

volumes:
  db-pg:
    driver: local