version: '3'

env:
  ENV: '.'

dotenv: [".env"]

tasks:
  run:
    dir: './cmd'
    cmds:
      - go run main.go {{.CLI_ARGS}}
    silent: true

  proto:
    dir: './pkg/grpc/proto'
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative *.proto
